[project]
name = "open-r1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "setuptools>=79.0.0",
    "trl>=0.16.1",
    "vllm==0.8.3",
]
