[project]
name = "open-r1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flash-attn>=2.7.4.post1",
    "setuptools>=79.0.0",
    "vllm==0.8.3",
]
